window.OZWOOD_DEMO = {
  rooms: {
    living: { label: "客厅", zh: "客厅", note: "悉尼开放式住宅空间" },
    bedroom: { label: "卧室", zh: "卧室", note: "安静舒适的私人空间" },
    study: { label: "书房", zh: "书房", note: "专注工作的家庭书房" }
  },
  products: [
    {
      key: "european-oak",
      code: "OAK 5106",
      name: "欧洲橡木 5106",
      shortName: "欧洲橡木",
      type: "工程木地板",
      tone: "温暖原木",
      price: 49,
      originalPrice: 68,
      priceNote: "官网产品页促销参考，需确认当前库存与价格",
      specification: "1200 × 163 × 12 mm",
      pack: "2.3472 m² / 箱",
      profile: "多层工程木结构",
      installationRate: 45,
      waste: 0.10,
      tags: ["真实木质感", "结构稳定", "家庭优选"],
      bestFor: ["客厅与餐厅", "全屋连续铺装", "温暖的现代空间"],
      avoid: "不建议把它直接理解为湿区地板；安装前应确认现场含水率与使用区域。",
      story: "一款平衡度很高的木地板：表层保留真实橡木的天然质感，多层结构则帮助它更稳定地应对季节变化。",
      why: "它能带来真实橡木的温度，又不会让空间过黄或过暗。当需求是“自然、安静、耐看”时，它是很稳妥的综合选择。",
      install: "先检测基层含水率并确认平整度，再由安装人员确定胶粘或悬浮铺装方式、伸缩缝与材料适应时间。",
      care: "定期吸走砂粒，使用微湿拖布和建议的木地板清洁剂，并避免地面积水。",
      officialImage: "assets/ozwood/official/product-european-oak.jpg",
      source: "https://ozwoodaustralia.com.au/product/oak-5106-france-78-m2/"
    },
    {
      key: "spotted-gum",
      code: "SG1443-185",
      name: "澳洲斑纹桉 SG1443-185",
      shortName: "澳洲斑纹桉",
      type: "澳洲硬木工程地板",
      tone: "浓郁澳洲木色",
      price: null,
      originalPrice: null,
      priceNote: "需向 Ozwood 获取当前报价",
      specification: "澳洲及进口硬木精品系列",
      pack: "需确认批次与包装规格",
      profile: "鲜明的澳洲天然木材个性",
      installationRate: 48,
      waste: 0.10,
      tags: ["澳洲木材个性", "坚硬耐用", "天然色差"],
      bestFor: ["高频使用的家庭客厅", "澳洲住宅风格", "需要温度与木材个性的空间"],
      avoid: "天然色差正是它的特点，并不是完全均一的颜色；决定前应同时查看多块实物板。",
      story: "Ozwood 的官网故事讲述了他们如何通过澳洲住宅重新认识 Spotted Gum：绿色、灰色与蜂蜜色的变化，加上本土性格、硬度和稳定性，让它成为长期受欢迎的选择。",
      why: "如果客户希望地板一眼就有澳洲木材的辨识度，接受明显木纹与颜色变化，而不是追求完全均一的表面，它会是最有说服力的推荐。",
      install: "铺装前确认楼板含水率、同批次色差与铺装方向。建议先将代表性板材进行预排，让最终色彩分布更自然。",
      care: "入口使用地垫，家具脚增加保护垫，及时清除砂粒和水渍，并遵循对应表面工艺的养护说明。",
      officialImage: "assets/ozwood/official/product-spotted-gum.jpg",
      source: "https://ozwoodaustralia.com.au/product-category/engineered-floor/premium-native-exotic-hardwood-14mm/"
    },
    {
      key: "herringbone",
      code: "OAK 4301",
      name: "工程橡木人字拼 4301",
      shortName: "橡木人字拼",
      type: "工程木拼花地板",
      tone: "烟熏建筑感",
      price: null,
      originalPrice: null,
      priceNote: "需获取供货与安装报价",
      specification: "人字拼花规格",
      pack: "需确认拼法、批次与损耗",
      profile: "精细拼花安装",
      installationRate: 75,
      waste: 0.15,
      tags: ["空间焦点", "经典拼法", "高端质感"],
      bestFor: ["重点客厅", "玄关入口", "设计主导型翻新"],
      avoid: "相比直铺会增加切割损耗与人工；中心线、边框和收口需要提前规划。",
      story: "人字拼把传统欧洲拼花和现代澳洲室内设计连接起来，能够为空间增加方向、层次与手工铺装的焦点感。",
      why: "当地面需要成为建筑设计的一部分，而不是一块中性的背景时，就应该优先考虑它。",
      install: "专业放线非常重要。报价前应确认视觉中心轴、周边切割、过渡收口、胶粘系统和额外损耗。",
      care: "避免砂粒和家具拖动损伤表面，并按照工程木地板的低水分方式进行日常养护。",
      officialImage: "assets/ozwood/official/product-herringbone.jpg",
      source: "https://ozwoodaustralia.com.au/parquetry/"
    },
    {
      key: "white-oak",
      code: "OZ2628",
      name: "OZ2628 白橡木",
      shortName: "白橡木",
      type: "12 mm 强化地板",
      tone: "明亮通透",
      price: 28.8,
      originalPrice: null,
      priceNote: "官网产品页参考，需确认当前价格",
      specification: "1215 × 197 × 12 mm",
      pack: "2.39 m² · 10 片 · 21 kg",
      profile: "锁扣安装 · 防潮耐水",
      installationRate: 30,
      waste: 0.08,
      tags: ["高性价比", "锁扣快装", "容易打理"],
      bestFor: ["明亮公寓", "卧室", "出租房与预算优先项目"],
      avoid: "防潮耐水不等于完全防水；可能出现持续积水的区域需要选择明确的防水系列。",
      story: "OZ 强化地板系列希望用快速锁扣安装和日常耐用性，以更实际的成本实现接近木材的视觉效果。",
      why: "它能让较暗或较小的空间显得更开阔，同时控制材料预算，又不会完全失去温暖的木质表达。",
      install: "检查基层平整度和含水率，使用指定地垫，正确错缝，并保留周边伸缩缝。",
      care: "经常吸尘或清扫，使用接近干燥的微湿拖布，避免蒸汽拖把，并及时处理水渍。",
      officialImage: "assets/ozwood/official/product-white-oak.jpg",
      source: "https://ozwoodaustralia.com.au/product/oz2618-bordeaux-oak/"
    },
    {
      key: "hybrid-grey",
      code: "HYBRID GREY OAK",
      name: "灰橡混合地板",
      shortName: "冷灰橡木",
      type: "6.5 mm 混合地板",
      tone: "冷灰现代",
      price: 19.8,
      originalPrice: 43,
      priceNote: "官网促销页参考，需确认当前库存与活动",
      specification: "1220 × 183 × 6.5 mm",
      pack: "2.2326 m² / 箱",
      profile: "E0 · AC4 · 防水",
      installationRate: 30,
      waste: 0.08,
      tags: ["防水", "AC4 耐磨", "价格友好"],
      bestFor: ["孩子与宠物家庭", "靠近厨房的客厅", "商用或投资房"],
      avoid: "仍需确认具体区域的湿区许可、周边密封和基层要求。",
      story: "混合地板将木纹表面与防水、耐磨结构结合起来。当生活便利性比天然木材的真实性更重要时，它非常实用。",
      why: "面对水渍、宠物、高频使用和较紧的材料预算，它是最稳妥的演示推荐；安静的冷灰色也适合现代空间。",
      install: "楼板仍需保持干燥、清洁和平整，并遵循产品对应的伸缩缝、地垫和周边密封要求。",
      care: "通常定期吸尘和微湿拖地即可；避免磨蚀性清洁剂，并遵循产品保修养护指南。",
      officialImage: "assets/ozwood/official/product-hybrid-grey.jpg",
      source: "https://ozwoodaustralia.com.au/product/hybrid-grey-oak/"
    }
  ],
  stories: [
    {
      id: "expertise",
      eyebrow: "OZWOOD 的承诺",
      title: "专业，让选择更安心",
      text: "Ozwood 将自己定位为悉尼木地板专业服务商，提供产品选择、供货与专业安装。官网目前介绍其已经服务超过 10,000 个悉尼家庭。",
      image: "assets/ozwood/official/story-flooring-journey.jpg",
      facts: ["服务 10,000+ 悉尼家庭", "木地板选择与供货", "经验丰富的安装团队"],
      source: "https://ozwoodaustralia.com.au/"
    },
    {
      id: "spotted",
      eyebrow: "一段木材故事",
      title: "重新认识澳洲斑纹桉",
      text: "Ozwood 最打动人的故事之一，是一次视角的改变：一位木材从业者来到悉尼，起初并不重视 Spotted Gum，后来才理解它的颜色变化、硬度与本土身份为什么如此适合澳洲住宅。",
      image: "assets/ozwood/official/story-spotted-gum.jpg",
      facts: ["绿色、灰色与蜂蜜色变化", "官网文章提到 11 kN Janka 硬度", "具有强烈澳洲身份的本土木材"],
      source: "https://ozwoodaustralia.com.au/2018/04/21/the-spotted-gum-i-know/"
    },
    {
      id: "healthy",
      eyebrow: "健康住宅",
      title: "先理解材料，而不只选择颜色",
      text: "Ozwood 的知识内容会引导客户同时考虑排放等级、材料结构和日常生活，而不只是外观。这套 Demo 把这些内容转化为孩子、宠物、清洁、潮湿和房间用途等实际问题。",
      image: "assets/ozwood/official/story-healthy-floor.png",
      facts: ["了解 E0 与排放声明", "让性能匹配使用空间", "确认具体产品检测资料"],
      source: "https://ozwoodaustralia.com.au/2017/11/15/for/"
    },
    {
      id: "journey",
      eyebrow: "完整决策过程",
      title: "选购 → 安装 → 养护",
      text: "选定颜色并不代表地板决策已经结束。Ozwood 的知识库围绕选对产品、正确准备与安装，以及长期养护三个阶段组织。",
      image: "assets/ozwood/official/story-client-journey.jpg",
      facts: ["空间与生活方式匹配", "基层和含水率检查", "低水分日常养护"],
      source: "https://ozwoodaustralia.com.au/knowledgebase/?id=tab_choosing"
    },
    {
      id: "showrooms",
      eyebrow: "亲眼看，亲手摸",
      title: "两家悉尼展厅",
      text: "数字推荐最终应该连接到真实的下一步：比较实物板，理解天然色差，并和 Ozwood 团队确认现场安装条件。",
      image: "assets/ozwood/official/story-barock.jpg",
      facts: ["Auburn · D2 / 290 Parramatta Road", "Castle Hill · 8/9 Salisbury Road", "免费咨询、样板或报价申请"],
      source: "https://ozwoodaustralia.com.au/contact/"
    }
  ],
  questions: [
    { id: "space", text: "先从项目类型开始：这次铺装是在什么空间？", options: ["独立屋", "公寓", "办公室或商用", "还没确定"] },
    { id: "room", text: "主要想改造哪个区域？我会同步切换到对应的概念场景。", options: ["客厅和餐厅", "卧室", "书房", "全屋统一"] },
    { id: "area", text: "大约需要铺多少平方米？这个会影响材料、损耗和预算估算。", options: ["约 30 m²", "约 60 m²", "约 100 m²", "暂时不清楚"] },
    { id: "style", text: "你希望空间呈现什么感觉？", options: ["明亮通透", "温暖自然", "澳洲木材个性", "人字拼设计感", "冷灰现代"] },
    { id: "lifestyle", text: "日常使用强度更接近哪一种？", options: ["有孩子和宠物", "人流较大 / 耐磨优先", "安静的成人家庭", "出租或投资房"] },
    { id: "subfloor", text: "现有基层是什么？不知道也没关系，现场测量时可以确认。", options: ["混凝土楼板", "现有瓷砖", "木基层", "不清楚"] },
    { id: "moisture", text: "这里对防水或防潮的要求高吗？", options: ["需要防水", "偶尔有水和清洁", "普通干区", "需要现场判断"] },
    { id: "service", text: "你希望 Ozwood 提供到哪一步？", options: ["供货 + 安装", "只需要供货", "先寄样板", "先到展厅看看"] },
    { id: "budget", text: "最后一个关键条件：每平方米材料预算大概是多少？", options: ["AU$35 以下", "AU$35–55", "AU$55 以上", "先看效果再报价"] }
  ]
};
